// Reducer Action Constants
export const IS_SENDING_AUTH_REQUEST = "IS_SENDING_AUTH_REQUEST";
export const SET_AUTH_REQUEST_ERROR = "SET_AUTH_REQUEST_ERROR";
export const CLEAR_AUTH_REQUEST_ERROR = "CLEAR_AUTH_REQUEST_ERROR";
export const SET_AUTH_REQUEST_SUCCESS = "SET_AUTH_REQUEST_SUCCESS";
export const CLEAR_AUTH_REQUEST_SUCCESS = "CLEAR_AUTH_REQUEST_SUCCESS";
export const SET_SELF_USER_TOKEN = "SET_SELF_USER_TOKEN";
export const SET_AUTH_FORM_EMAIL = "SET_AUTH_FORM_EMAIL";
export const SET_AUTH_FORM_USERNAME = "SET_AUTH_FORM_USERNAME";
export const SET_AUTH_FORM_PASSWORD = "SET_AUTH_FORM_PASSWORD";
export const SET_AUTH_FORM_PASSWORD_CONFIRMATION = "SET_AUTH_FORM_PASSWORD_CONFIRMATION";
export const SET_AUTH_FORM_OLD_PASSWORD = "SET_AUTH_FORM_OLD_PASSWORD";

// Saga Action Constants
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const EMAIL_VERIFICATION_REQUEST = "EMAIL_VERIFICATION_REQUEST";
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
