// Reducer actions
export const IS_SENDING_GOAL_REQUEST = "IS_SENDING_GOAL_REQUEST";
export const SET_GOAL_REQUEST_ERROR = "SET_GOAL_REQUEST_ERROR";
export const CLEAR_GOAL_REQUEST_ERROR = "CLEAR_GOAL_REQUEST_ERROR";
export const SET_GOAL_REQUEST_SUCCESS = "SET_GOAL_REQUEST_SUCCESS";
export const CLEAR_GOAL_REQUEST_SUCCESS = "CLEAR_GOAL_REQUEST_SUCCESS";

// Saga actions
export const CREATE_GOAL_REQUEST = "CREATE_GOAL_REQUEST";
export const GET_GOALS_REQUEST = "GET_GOALS_REQUEST";
export const GET_GOAL_REQUEST = "GET_GOAL_REQUEST";
export const UPDATE_GOAL_REQUEST = "UPDATE_GOAL_REQUEST";
export const DELETE_GOAL_REQUEST = "DELETE_GOAL_REQUEST";
