// Reducer actions
export const IS_SENDING_GOAL_REQUEST = "IS_SENDING_GOAL_REQUEST";
export const SET_GOAL_REQUEST_ERROR = "SET_GOAL_REQUEST_ERROR";
export const CLEAR_GOAL_REQUEST_ERROR = "CLEAR_GOAL_REQUEST_ERROR";
export const SET_GOAL_REQUEST_SUCCESS = "SET_GOAL_REQUEST_SUCCESS";
export const CLEAR_GOAL_REQUEST_SUCCESS = "CLEAR_GOAL_REQUEST_SUCCESS";
export const CLEAR_GOALS_PAGINATION = "CLEAR_GOALS_PAGINATION";
export const SET_GOALS = "SET_GOALS";
export const ADD_GOALS = "ADD_GOALS";
export const ADD_GOAL = "ADD_GOAL";
export const REMOVE_GOAL = "REMOVE_GOAL";
export const SET_GOAL_ID = "SET_GOAL_ID";
export const SET_GOAL_USER_ID = "SET_GOAL_USER_ID";
export const SET_GOAL_NAME = "SET_GOAL_NAME";
export const SET_GOAL_TAG = "SET_GOAL_TAG";
export const SET_GOAL_ADDITIONAL_INFO = "SET_GOAL_ADDITIONAL_INFO";

// Saga actions
export const CREATE_GOAL_REQUEST = "CREATE_GOAL_REQUEST";
export const GET_GOALS_REQUEST = "GET_GOALS_REQUEST";
export const GET_GOAL_REQUEST = "GET_GOAL_REQUEST";
export const GET_EDITABLE_GOAL_REQUEST = "GET_EDITABLE_GOAL_REQUEST";
export const UPDATE_GOAL_REQUEST = "UPDATE_GOAL_REQUEST";
export const DELETE_GOAL_REQUEST = "DELETE_GOAL_REQUEST";
